[project]
name = "mcp-client"
version = "0.1.0"
description = "Simple MCP client for DeepL translation with VS Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.9.3",
    "python-dotenv>=1.1.0",
]
